### ISSUE TITLE
[feature] MRC (manual reference counting) compatibility would be great

### ISSUE THREAD

**Issue by nros** [jverdi/JVAlertController#10]
This backport of UIAlertController really is a life-saver. At least it was to me! Many thanks for your great work!

Unfortunately I have to maintain a legacy app that still uses MRC instead of ARC. Until April 2015 the app still supported iOS4 for iPad1. iOS4 does not provide ARC.

So I need a version of this library to cope with MRC and tried to implement it properly but keeping the impact as low as possible. I had to reorganize some code, though, which made it a bit more complex.
Please review my changes. I would be grateful if you could include my patch for others with the same problem.

**Comment by jverdi** [comment]
Glad you could make use of it! And thanks for the work you've contributed back.

I feel your pain here, but having to maintain MRC compatibility in the master branch/cocoapod would add a hefty maintenance cost -- and the potential for new bugs. As it is, this is really just serving as a shim for me until its commonplace to drop iOS 7 support.

That said, I wouldn't mind making this contribution more readily available in a separate "mrc" branch, if you're willing to retarget your pull request.

**Comment by nros** [comment]
I will happily do!
Nevertheless I am not very familiar with re-targeting a pull request. From what I have learned through searching with a search engine, I think we need to:

```
I will close this pull request
you need to create the target branch
I create a new pull request.
```

Is this correct?

**Comment by jverdi** [comment]
@nros Ok, I've added a branch "manual-reference-counting" that you can target.

**Comment by jverdi** [comment]
Added via PR #12 as branch "manual-reference-counting"
