### ISSUE TITLE
implement iOS 5 support

### ISSUE THREAD

**Issue by nros** [jverdi/JVAlertController#13]
# iPad 1 not to be forgotten ...
## current state of iPad 1 devices

All iPad 1 are stuck with iOS 5. They'll never get an update to any newer iOS.
It would be great to have iOS 5 support with `JVAlertController` and I am working on it. 
## iOS compatibility is partly working on developer machine

In fact, I managed to run the code on iOS 5 and implement the look of the `UIActionSheet` within a popover.

I'll prepare everything for a pull request.
## new branch wanted for legacy iOS SDK?

Unfortunately my iPad 1 broke couple of weeks ago, so I have to rely on the iOS simulator, which I have to run on OSX 10.7 with Xcode4, because there is no iOS5 simulator available anymore on modern OS X or modern Xcode.

Because of the old simulator I have to compile with an old iOS SDK (<= 6) which lacks some protocols and classes involved. I managed to add everything that is needed to run `JVAlertController` and store all these things inside a sub-directory "legacy-iOS-SDK".

Do you prefer to put changes necessary solely to compile with legacy iOS SDK in a separate branch? IMHO legacy iOS SDK support is vital to test for iPad 1 with iOS 5 simulator, so it would be nice to include it in the main branch. These back ported files will hardly change in the future.
## what is working
- At the moment I concentrated to mimic the `UIActionSheet` displayed in a popover. This works from iOS 5 to iOS 8 with proper look!
## what is not working
- tint color is not working on iOS 5/6. A custom background image would be needed to implement that reliable - I think we can live without it :)
## what is missing
- AlertView is still work in progress
- I will have to add a separate Xcode4 project settings file for testing everything on iOS5 simulator.

**Comment by jverdi** [comment]
I commend your effort :) but I think the large majority of the iOS community has moved to an iOS 7 baseline. This is not likely to reach a large enough audience to be worth the maintenance costs. I would suggest to keep it all in one legacy support branch with the understanding that that branch is not officially supported.

**Comment by nros** [comment]
I'm fine with it - thanks! I will try to keep that branch up to date with the main-branch until I'll drop iPad1 support with my app, which I do not plan to do soon.

Do you create such a "legacy" branch as target for my pull request?
I need another week to test the alert messages, though.

**Comment by jverdi** [comment]
@nros I've renamed the "mrc" branch to "legacy". You can combine both efforts there.
